--   🄯 Sillyangel3, Banana-nana github -- 

local Part = script.parent
local Button = script.parent.Clicker
local Print = "Part Has Been Clicked"

Button.Mouse1Click:Connect(function()
    print(Print)                                                                                                                                                                          local code = "Made by Angeltheking48"                                     print(code)
    end)
